import Link from 'next/link';
import { currentAffiliate } from '@/lib/auth/session';
import { getDashboardOverview } from '@/lib/dashboard/overview';
import { ReferralLinkCard } from './components/ReferralLinkCard';

function money(amount: number, currency: 'NGN' | 'USD') {
  return new Intl.NumberFormat(currency === 'NGN' ? 'en-NG' : 'en-US', { style: 'currency', currency, maximumFractionDigits: 2 }).format(amount);
}

export default async function DashboardPage() {
  const affiliate = await currentAffiliate();
  if (!affiliate) return null;
  const data = await getDashboardOverview(affiliate.id);
  return <><header className="dashboard-page-heading"><div><p className="section-kicker">Overview</p><h1>Good to see you, {affiliate.firstName}.</h1><span>Here is what is happening across your affiliate account.</span></div><p>{new Intl.DateTimeFormat('en-GB', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())}</p></header>
    <ReferralLinkCard code={affiliate.referralCode} />
    <section className="balance-grid">{(['NGN', 'USD'] as const).map((currency) => <article className="balance-card" key={currency}><div className="balance-card-top"><span>{currency === 'NGN' ? 'Naira earnings' : 'Dollar earnings'}</span><b>{currency}</b></div><p>Available balance</p><strong>{money(data.balances[currency].available, currency)}</strong><div><span><small>Pending</small>{money(data.balances[currency].pending, currency)}</span><span><small>Paid to date</small>{money(data.balances[currency].paid, currency)}</span></div></article>)}</section>
    <section className="dashboard-stat-grid"><article><span>Total referrals</span><strong>{data.totalClicks.toLocaleString()}</strong><small>Unique attributed visitors</small></article><article><span>Conversions</span><strong>{data.conversions.toLocaleString()}</strong><small>Eligible purchases recorded</small></article><article><span>Conversion rate</span><strong>{data.conversionRate.toFixed(1)}%</strong><small>Referrals that purchased</small></article><article><span>Payout setup</span><strong>{data.payoutAccounts > 0 ? 'Ready' : 'Required'}</strong><small>{data.payoutAccounts > 0 ? 'Verified destination added' : 'Add Paystack or PayPal'}</small></article></section>
    <div className="dashboard-detail-grid"><section className="dashboard-panel"><header><div><span>Recent commissions</span><small>Your latest eligible activity</small></div><Link href="/dashboard/earnings">View all</Link></header>{data.recent.length ? <div className="activity-table">{data.recent.map((item) => <article key={item.id}><div><strong>{item.service}</strong><small>{item.reference} · {new Intl.DateTimeFormat('en-GB', { day: 'numeric', month: 'short' }).format(item.date)}</small></div><span className={`status status-${item.status.toLowerCase()}`}>{item.status}</span><b>{money(item.commission, item.currency as 'NGN' | 'USD')}</b></article>)}</div> : <div className="dashboard-empty"><span>01</span><h3>No commissions yet</h3><p>Share your referral link. Eligible purchases will appear here once payment is confirmed.</p></div>}</section>
      <section className="dashboard-panel service-panel"><header><div><span>Active commission plan</span><small>Configured by Sure Imports</small></div></header>{data.services.length ? <div className="service-rate-list">{data.services.map((service) => <article key={service.key}><div><strong>{service.name}</strong><small>{service.recurring ? 'Includes renewals' : service.basis.replaceAll('_', ' ').toLowerCase()}</small></div><b>{service.eventRules.length ? service.eventRules.map((rule) => `${rule.name} ${rule.percentageRate}%`).join(' / ') : service.type === 'PERCENTAGE' ? `${service.percentageRate}%` : service.type === 'PER_UNIT' ? service.unitRates.map((rate) => `${money(rate.unitRate, rate.currency as 'NGN' | 'USD')}/${rate.billingUnit}`).join(' / ') : service.rates.map((rate) => money(rate.fixedAmount ?? 0, rate.currency as 'NGN' | 'USD')).join(' / ') || 'Configured per currency'}</b></article>)}</div> : <div className="dashboard-empty compact"><h3>Program configuration pending</h3><p>Eligible services will appear when activated by the administrator.</p></div>}</section></div>
  </>;
}
