const lines = [
  '# Sure Imports Partner Shipping API — Developer Quickstart',
  '',
  'Use this guide to connect a server-side application to Sure Imports and create shipping-only requests that remain permanently attributed to the referring affiliate.',
  '',
  '## Before you begin',
  '',
  '1. Ask the affiliate to create an API key in Affiliate Dashboard → Developers.',
  '2. Transfer the key through a secure channel. It is displayed only once.',
  '3. Store it in a server-side secret manager or encrypted environment variable.',
  '4. Never place it in browser JavaScript, a mobile application bundle, logs, screenshots, or a public repository.',
  '',
  'Production base URL: `https://www.sureimports.com/api/v1`',
  '',
  'Machine-readable specification: `https://www.sureimports.com/api/v1/openapi`',
  '',
  '## Authentication',
  '',
  'Send the API key as a Bearer token on every request:',
  '',
  '```http',
  'Authorization: Bearer si_live_REPLACE_ME',
  '```',
  '',
  'Keys currently carry `shipping:write` and `shipping:read` scopes. A revoked or expired key immediately stops working.',
  '',
  '## 1. Discover shipping plans',
  '',
  'Always retrieve the current plan ID and billing unit before submitting a request.',
  '',
  '```bash',
  'curl --request GET "https://www.sureimports.com/api/v1/shipping-plans?destinationCountry=Nigeria" \\',
  '  --header "Authorization: Bearer si_live_REPLACE_ME"',
  '```',
  '',
  'Each plan returns a `shippingPlanId` and a `billingUnit`. Submit estimated quantity in that exact unit. Nigeria sea shipping is returned as `CBM`; per-weight plans are returned as `KG`.',
  '',
  '## 2. Create an owned shipping request',
  '',
  '```bash',
  'curl --request POST "https://www.sureimports.com/api/v1/shipping-requests" \\',
  '  --header "Authorization: Bearer si_live_REPLACE_ME" \\',
  '  --header "Idempotency-Key: partner-order-88421" \\',
  '  --header "Content-Type: application/json" \\',
  '  --data \'{',
  '    "customer": {',
  '      "firstName": "Ada",',
  '      "lastName": "Okafor",',
  '      "email": "ada@example.com",',
  '      "phone": "+2348012345678"',
  '    },',
  '    "shipment": {',
  '      "shippingName": "Ada Stores",',
  '      "destinationCountry": "Nigeria",',
  '      "shippingPlanId": "REPLACE_WITH_PLAN_ID",',
  '      "estimatedQuantity": 32.5,',
  '      "description": "Two cartons of fashion accessories",',
  '      "expectedShipments": "Ready for collection in Guangzhou",',
  '      "wantProductVerification": false,',
  '      "wantConsolidation": false,',
  '      "multipleSuppliers": false',
  '    },',
  '    "externalReference": "partner-order-88421"',
  '  }\'',
  '```',
  '',
  'Required fields:',
  '',
  '- `customer.firstName`',
  '- `customer.email`',
  '- `customer.phone`',
  '- `shipment.shippingName`',
  '- `shipment.destinationCountry`',
  '- `shipment.shippingPlanId`',
  '- `shipment.estimatedQuantity`',
  '- `shipment.description`',
  '- `externalReference`',
  '',
  'A successful request returns HTTP 201 with `requestId`, `externalReference`, `status`, `customerId`, `ownership.attributionId`, and `ownership.lockedAt`.',
  '',
  '## 3. Read request status',
  '',
  '```bash',
  'curl --request GET "https://www.sureimports.com/api/v1/shipping-requests/REQUEST_ID" \\',
  '  --header "Authorization: Bearer si_live_REPLACE_ME"',
  '```',
  '',
  'An API key can read only requests owned by the same affiliate account.',
  '',
  '## Idempotency and references',
  '',
  '- Every POST requires an `Idempotency-Key` containing 8–120 characters.',
  '- Use one stable idempotency key for one logical submission.',
  '- Retrying the same payload with the same key returns the original response.',
  '- Reusing the key with different content returns HTTP 409.',
  '- `externalReference` must also be unique for that affiliate and should match the request ID in the partner system.',
  '- For a temporary server or network error, retry with the same idempotency key.',
  '',
  '## Affiliate ownership and commission',
  '',
  '- The API key identifies the affiliate. Never send an affiliate ID in the customer payload.',
  '- Ownership is locked when Sure Imports accepts the request and cannot be reassigned by the customer.',
  '- This request-specific ownership does not replace the customer’s general affiliate relationship.',
  '- The request estimate does not determine commission.',
  '- When the related invoice is fully paid, Sure Imports calculates commission from the final billable KG or CBM and the configured rate for the invoice currency.',
  '- Naira invoices create Naira commissions; USD invoices create USD commissions.',
  '- Duties, storage, verification, penalties, and unrelated charges are excluded.',
  '- Cancelled or reversed payments void the associated commission.',
  '',
  '## Error responses',
  '',
  '| HTTP | Code | Meaning |',
  '| --- | --- | --- |',
  '| 400 | `INVALID_REQUEST` | Fields, country, plan, or quantity are invalid. |',
  '| 401 | `UNAUTHORIZED` | API key is missing, invalid, expired, or revoked. |',
  '| 403 | `INSUFFICIENT_SCOPE` | API key lacks the required scope. |',
  '| 404 | `NOT_FOUND` | The request does not exist or belongs to another affiliate. |',
  '| 409 | `IDEMPOTENCY_CONFLICT` | The idempotency key was reused with different content. |',
  '| 409 | `EXTERNAL_REFERENCE_CONFLICT` | The external reference already identifies another request. |',
  '| 429 | `RATE_LIMITED` | Slow down and respect the `Retry-After` header. |',
  '| 500 | `INTERNAL_ERROR` | The operation could not be completed safely. |',
  '| 503 | `SERVICE_UNAVAILABLE` | Retry later with the same idempotency key. |',
  '',
  '## Handoff checklist',
  '',
  '- [ ] Key is stored only on the server.',
  '- [ ] Shipping plans are discovered dynamically.',
  '- [ ] `estimatedQuantity` uses the returned `billingUnit`.',
  '- [ ] Idempotency keys are stable across retries.',
  '- [ ] External references map back to partner records.',
  '- [ ] Logs redact the Authorization header and customer personal information.',
  '- [ ] 429 and 503 responses use controlled retry logic.',
  '',
  'Generated by the Sure Imports Affiliate developer workspace.',
];

export const partnerApiQuickstartMarkdown = `${lines.join('\n')}\n`;
